#!/bin/bash

gcc -I/opt/jdk1.7/include -I/opt/jdk1.7/include/linux -I/opt/cuda/include -I/usr/local/dcs/versions/jdk1.7.0_51_x64/include -I/usr/local/dcs/versions/jdk1.7.0_51_x64/include/linux -I/usr/local/cuda/include -shared -fPIC -o libEduRitGpuCuda.so edu_rit_gpu_Cuda.c -lcuda
